export const MEMO_POST = "MEMO_POST";
export const MEMO_POST_SUCCESS = "MEMO_POST_SUCCESS";
export const MEMO_POST_FAILURE = "MEMO_POST_FAILURE";

export const MEMO_LIST = "MEMO_LIST";
export const MEMO_LIST_SUCCESS = "MEMO_LIST_SUCCESS";
export const MEMO_LIST_FAILURE = "MEMO_LIST_FAILURE";

export const MEMO_REMOVE = "MEMO_REMOVE";
export const MEMO_REMOVE_SUCCESS = "MEMO_REMOVE_SUCCESS";
export const MEMO_REMOVE_FAILURE = "MEMO_REMOVE_FAILURE";

export const PASSWORD_CHECK = "PASSWORD_CHECK";
export const PASSWORD_CHECK_SUCCESS = "PASSWORD_CHECK_SUCCESS";
export const PASSWORD_CHECK_FAILURE = "PASSWORD_CHECK_FAILURE";

export const MEMO_EDIT = "MEMO_EDIT";
export const MEMO_EDIT_SUCCESS = "MEMO_EDIT_SUCCESS";
export const MEMO_EDIT_FAILURE = "MEMO_EDIT_FAILURE";

export const IMAGE_UPLOAD = "IMAGE_UPLOAD";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAILURE = "IMAGE_UPLOAD_FAILURE";

export const IMAGE_GALLERY_LIST = "IMAGE_GALLERY_LIST";
export const IMAGE_GALLERY_LIST_SUCCESS = "IMAGE_GALLERY_LIST_SUCCESS";
export const IMAGE_GALLERY_LIST_FAILURE = "IMAGE_GALLERY_LIST_FAILURE";

export const IMAGE_GRID_LIST = "IMAGE_GRID_LIST";
export const IMAGE_GRID_LIST_SUCCESS = "IMAGE_GRID_LIST_SUCCESS";
export const IMAGE_GRID_LIST_FAILURE = "IMAGE_GRID_LIST_FAILURE";

export const VIDEO_LIST = "VIDEO_LIST";
export const VIDEO_LIST_SUCCESS = "VIDEO_LIST_SUCCESS";
export const VIDEO_LIST_FAILURE = "VIDEO_LIST_FAILURE";

export const KAKAO_LOGIN = "KAKAO_LOGIN";
export const KAKAO_LOGIN_SUCCESS = "KAKAO_LOGIN_SUCCESS";
export const KAKAO_LOGIN_FAILURE = "KAKAO_LOGIN_FAILURE";

export const KAKAO_LOGOUT = "KAKAO_LOGOUT";
export const KAKAO_LOGOUT_SUCCESS = "KAKAO_LOGOUT_SUCCESS";
export const KAKAO_LOGOUT_FAILURE = "KAKAO_LOGOUT_FAILURE";


